- name: "Create NFS Mount points"
  file:
    path: /mnt/asgard
    state: directory
    mode: "777"
    group: nobody:nogroup
  shell:
    executable: /bin/bash
    cmd: "sudo chown nobody:nogroup /mnt/asgard"
