utilityPackages:
  - unzip
  - curl
  - zip
  - software-properties-common
  - build-essential
  - procps
  - file
  - git
  - python3-pip

avahiPackages:
  - avahi-daemon

nfsPackages:
  - nfs-common
