- name: "Create nfs mounting directories"
  file:
    path: /mnt/asgard_client
    state: directory

- name: "Set fstab configuration"
  file:
    backup: true
    boot: true
    fstype: nfs
    path: /mnt/asgard_client
    src: 192.168.102.1:/mnt/asgard
    dump: "0"
    state: present
