---
  - name: "Configure Ubuntu (SUDO)"
    hosts: [localhost]
    connection: local

    tasks:
    - name: "Create NFS Mount points"
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /mnt/asgard

    - name: "Update APT Cache"
      apt:
        update_cache: yes
        autoclean: true

    - name: "Upgrade Packages"
      apt:
        upgrade: safe
        autoremove: true
        purge: true

    - name: "Upgrade System Packages"
      apt:
        upgrade: full
        autoremove: true
        purge: true

    - name: "Upgrade Distribution"
      apt:
        upgrade: dist
        autoremove: true
        purge: true

    - name: "Update APT Cache"
      apt:
        update_cache: yes
        autoclean: true

    - name: "Install Utilities"
      apt:
        name: ["unzip", "curl", "zip", "software-properties-common", "build-essential", "procps", "file", "git"]

    - name: "Install avahi"
      apt:
        name: ["avahi-daemon"]

    - name: "Install NFS"
      apt:
        name: ["nfs-kernel-server"]

    - name: "Install dnsmasq"
      apt:
        name: ["dnsmasq", "dnsutils", "ldnsutils"]

    - name: "Enable avahi-daemon"
      service:
        name: avahi-daemon
        state: started

    - name: "Backup dnsmasq configuration files [0]"
      copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.backup
        backup: yes

    - name: "Backup dnsmasq configuration files [1]"
      copy:
        src: /etc/host.conf
        dest: /etc/host.conf.backup
        backup: yes

    - name: "Backup dnsmasq configuration files [2]"
      copy:
        src: /etc/dnsmasq.conf
        dest: /etc/dnsmasq.conf.backup
        backup: yes
